"""The OKF §8 root `index.md`: one line per concept, grouped, for progressive
disclosure -- an agent reads this first and opens only what it needs.

A derived navigation file, not a carrier. It is rebuilt from the bundle's own
files after they merge, never from a producer's projection, and `--check` lets
CI fail when it drifts; the concept file stays the source of truth. kbforge
cannot emit it per run: each system publishes on its own sync branch, and one
whole-bundle file on several branches is the one-path-two-owners collision.

No frontmatter, not even the optional root `okf_version`: a reserved name that
opens a fence is a concept (`parse.is_reserved`), so a fenced index would load
as one and count itself."""

from __future__ import annotations

import json
from pathlib import Path

from okfquery.load import load
from okfquery.parse import OKF_OWNED

INDEX = "index.md"
MARKER = "<!-- generated by okfquery index; do not edit, regenerate instead -->"
"""First line of every generated index. `write_index` only replaces a file that
starts with it, so a hand-curated index is never silently overwritten."""


class HandWrittenIndexError(Exception):
    """An existing `index.md` without the marker: someone wrote it by hand."""


def _link_text(text: str) -> str:
    # Backslash first, so the escapes added after it are not doubled. A backtick
    # would open a code span that outranks the link, and `<` inline HTML.
    for char in "\\[]`<":
        text = text.replace(char, "\\" + char)
    return text


_UNSAFE = frozenset(' #?%()<>[]\\"`{}|^')
"""What would end, redirect or garble a CommonMark link destination: space and
parentheses end it, `#` and `?` start a fragment or a query, `%` would read as
an escape, the rest are not allowed bare. Everything else stays as written."""


def _target(path: str) -> str:
    # Encode only what would break the link, not everything `quote` would: an
    # agent reads index.md as text and opens the path it sees, and a URL-derived
    # path like `concepts/@en.wikipedia.org/...` must not come out as `%40`.
    return "".join(
        "".join(f"%{b:02X}" for b in c.encode("utf-8"))
        if c in _UNSAFE or ord(c) < 0x21 or ord(c) == 0x7F
        else c
        for c in path
    )


def _one_line(text: str | None) -> str:
    """However the YAML wrapped it: an entry and a heading are one line each."""
    return " ".join((text or "").split())


def entry(path: str, title: str | None, description: str | None) -> str:
    line = f"* [{_link_text(_one_line(title) or path)}]({_target(path)})"
    summary = _one_line(description)
    return f"{line} - {summary}" if summary else line


def _label(value: object) -> str:
    # JSON spelling for scalars, so a YAML `true` heads a section as `true`, not
    # Python's `True`; strings as themselves.
    return value if isinstance(value, str) else json.dumps(value)


def _labels(values: list[object]) -> list[str]:
    labels = (_one_line(_label(v)) for v in values if v is not None)
    return sorted({label for label in labels if label})


def facet_values(facets: str | dict | None, key: str) -> list[str]:
    """One facet's values as sorted labels; a scalar is a one-value list and an
    empty value counts as missing. Shared by `index --group-by` and `related`,
    so "shares a tag" and "listed under the same heading" cannot disagree."""
    if isinstance(facets, str):  # DuckDB hands a JSON column back as text
        facets = json.loads(facets)
    value = facets.get(key) if isinstance(facets, dict) else None
    return _labels(value if isinstance(value, list) else [value])


def _groups(
    type_: str | None, facets: str | dict | None, group_by: str | None
) -> list[str]:
    """The sections a concept is listed under; [] means the trailing one. A list
    facet (tags, say) lists the concept once under each of its values, so
    concepts sharing a tag share a section."""
    if group_by is None:
        return _labels([type_])
    return facet_values(facets, group_by)


def render_bundle(bundle: Path, group_by: str | None = None) -> str:
    """The index for `bundle`, byte-for-byte deterministic: no timestamp, and
    every ordering is total, so CI commits only when a listing changed."""
    if group_by in OKF_OWNED:
        # Those keys never reach `facets`, so grouping on one would put every
        # concept in the trailing section and look like it worked.
        raise ValueError(
            f"{group_by!r} is not a facet: OKF owns it"
            + ("; omit --group-by to section by type" if group_by == "type" else "")
        )
    rows = (
        load(bundle)
        .execute("select path, type, title, description, facets from concepts")
        .fetchall()
    )
    groups: dict[str | None, list[tuple[str, str | None, str | None]]] = {}
    for path, type_, title, description, facets in rows:
        for key in _groups(type_, facets, group_by) or [None]:
            groups.setdefault(key, []).append((path, title, description))

    lines = [MARKER]
    # Named groups by name; the concepts missing the key go last, together.
    for key in sorted(groups, key=lambda k: (k is None, k or "")):
        heading = key if key is not None else f"(no {group_by or 'type'})"
        entries = sorted(
            groups[key], key=lambda e: ((_one_line(e[1]) or e[0]).casefold(), e[0])
        )
        lines += ["", f"# {heading}", ""]
        lines += [entry(*e) for e in entries]
    return "\n".join(lines) + "\n"


def write_index(bundle: Path, group_by: str | None = None, force: bool = False) -> bool:
    """Write `<bundle>/index.md`; True if the file changed. An identical file
    is left alone, so a no-op run leaves nothing for CI to commit."""
    target = bundle / INDEX
    text = render_bundle(bundle, group_by)
    if target.exists():
        current = target.read_text("utf-8", errors="replace")
        if not force and not current.startswith(MARKER):
            raise HandWrittenIndexError(
                f"{target} was not generated by okfquery; pass --force to replace it"
            )
        if current == text:
            return False
    target.write_text(text, "utf-8")
    return True


def is_generated(bundle: Path) -> bool:
    """False for a hand-written `index.md`, which `write_index` refuses."""
    target = bundle / INDEX
    return not target.exists() or target.read_text(
        "utf-8", errors="replace"
    ).startswith(MARKER)


def is_current(bundle: Path, group_by: str | None = None) -> bool:
    target = bundle / INDEX
    if not target.exists():
        return False
    return target.read_text("utf-8", errors="replace") == render_bundle(
        bundle, group_by
    )
