"""The OKF §8 root `index.md`: one line per concept, grouped, for progressive
disclosure -- an agent reads this first and opens only what it needs.

A derived navigation file, not a carrier. It is rebuilt from the bundle's own
files after they merge, never from a producer's projection, and `--check` lets
CI fail when it drifts; the concept file stays the source of truth. kbforge
cannot emit it per run: each system publishes on its own sync branch, and one
whole-bundle file on several branches is the one-path-two-owners collision.

No frontmatter, not even the optional root `okf_version`: a reserved name that
opens a fence is a concept (`parse.is_reserved`), so a fenced index would load
as one and count itself."""

from __future__ import annotations

import json
from pathlib import Path

from okfquery.load import load

INDEX = "index.md"
MARKER = "<!-- generated by okfquery index; do not edit, regenerate instead -->"
"""First line of every generated index. `write_index` only replaces a file that
starts with it, so a hand-curated index is never silently overwritten."""


class HandWrittenIndexError(Exception):
    """An existing `index.md` without the marker: someone wrote it by hand."""


def _link_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def _target(path: str) -> str:
    # CommonMark: a destination with spaces or parentheses must be <bracketed>.
    return f"<{path}>" if any(c in path for c in " ()<>") else path


def _entry(path: str, title: str | None, description: str | None) -> str:
    line = f"* [{_link_text(title or path)}]({_target(path)})"
    summary = " ".join((description or "").split())  # one line, however it wrapped
    return f"{line} - {summary}" if summary else line


def _group(type_: str | None, facets: object, group_by: str | None) -> str | None:
    if group_by is None:
        return type_
    if isinstance(facets, str):  # DuckDB hands a JSON column back as text
        facets = json.loads(facets)
    value = facets.get(group_by) if isinstance(facets, dict) else None
    return None if value is None else str(value)


def render_bundle(bundle: Path, group_by: str | None = None) -> str:
    """The index for `bundle`, byte-for-byte deterministic: no timestamp, and
    every ordering is total, so CI commits only when a listing changed."""
    rows = (
        load(bundle)
        .execute("select path, type, title, description, facets from concepts")
        .fetchall()
    )
    groups: dict[str | None, list[tuple[str, str | None, str | None]]] = {}
    for path, type_, title, description, facets in rows:
        key = _group(type_, facets, group_by)
        groups.setdefault(key, []).append((path, title, description))

    lines = [MARKER]
    # Named groups by name; the concepts missing the key go last, together.
    for key in sorted(groups, key=lambda k: (k is None, k or "")):
        heading = key if key is not None else f"(no {group_by or 'type'})"
        entries = sorted(groups[key], key=lambda e: ((e[1] or e[0]).casefold(), e[0]))
        lines += ["", f"# {heading}", ""]
        lines += [_entry(*e) for e in entries]
    return "\n".join(lines) + "\n"


def write_index(bundle: Path, group_by: str | None = None, force: bool = False) -> bool:
    """Write `<bundle>/index.md`; True if the file changed. An identical file
    is left alone, so a no-op run leaves nothing for CI to commit."""
    target = bundle / INDEX
    text = render_bundle(bundle, group_by)
    if target.exists():
        current = target.read_text("utf-8", errors="replace")
        if not force and not current.startswith(MARKER):
            raise HandWrittenIndexError(
                f"{target} was not generated by okfquery; pass --force to replace it"
            )
        if current == text:
            return False
    target.write_text(text, "utf-8")
    return True


def is_current(bundle: Path, group_by: str | None = None) -> bool:
    target = bundle / INDEX
    if not target.exists():
        return False
    return target.read_text("utf-8", errors="replace") == render_bundle(
        bundle, group_by
    )
