"""`okfquery index`: the OKF §8 root index.md, for agents that start cold."""

from __future__ import annotations

from pathlib import Path

import pytest

from okfquery.cli import main
from okfquery.index import MARKER, HandWrittenIndexError, render_bundle, write_index
from okfquery.load import load

MESSY = Path(__file__).parent / "fixtures" / "messy"


def _concept(bundle: Path, slug: str, **front: str) -> None:
    body = "".join(f"{k}: {v}\n" for k, v in front.items())
    path = bundle / "concepts" / slug / "overview.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"---\n{body}---\nBody of {slug}.\n", "utf-8")


@pytest.fixture
def bundle(tmp_path: Path) -> Path:
    _concept(tmp_path, "ledger", type="application", title="Ledger",
             description='"Book of\\n  record."', owner="finance")  # fmt: skip
    _concept(tmp_path, "fraud", type="application", title="Fraud Check",
             description="Scores payments.", owner="risk")  # fmt: skip
    _concept(tmp_path, "refunds", type="runbook", title="Refund a payment",
             owner="finance")  # fmt: skip
    _concept(tmp_path, "loose", title="Loose end", description="No type.")
    return tmp_path


def test_sections_by_type_entries_by_title_missing_type_last(bundle):
    text = render_bundle(bundle)
    assert text == (
        f"{MARKER}\n"
        "\n"
        "# application\n"
        "\n"
        "* [Fraud Check](concepts/fraud/overview.md) - Scores payments.\n"
        "* [Ledger](concepts/ledger/overview.md) - Book of record.\n"
        "\n"
        "# runbook\n"
        "\n"
        "* [Refund a payment](concepts/refunds/overview.md)\n"
        "\n"
        "# (no type)\n"
        "\n"
        "* [Loose end](concepts/loose/overview.md) - No type.\n"
    )


def test_group_by_a_facet(bundle):
    text = render_bundle(bundle, group_by="owner")
    sections = [line for line in text.splitlines() if line.startswith("# ")]
    assert sections == ["# finance", "# risk", "# (no owner)"], text


def test_an_unparseable_concept_is_still_listed_by_its_path():
    text = render_bundle(MESSY)
    assert "* [concepts/badyaml/overview.md](concepts/badyaml/overview.md)" in text
    assert "* [OK](concepts/ok/overview.md) - Fine." in text
    # Reserved, fenceless files are not concepts and must not be listed.
    assert "(concepts/log.md)" not in text
    assert "(concepts/index.md)" not in text


def test_brackets_in_a_title_do_not_break_the_link(tmp_path):
    _concept(tmp_path, "x", title="'Plan [draft]'")
    assert "* [Plan \\[draft\\]](concepts/x/overview.md)" in render_bundle(tmp_path)


def test_write_is_deterministic_and_does_not_count_itself(bundle):
    before = load(bundle).execute("select count(*) from concepts").fetchone()
    assert write_index(bundle) is True
    first = (bundle / "index.md").read_bytes()
    assert write_index(bundle) is False, "an unchanged index must not be rewritten"
    assert (bundle / "index.md").read_bytes() == first
    after = load(bundle).execute("select count(*) from concepts").fetchone()
    assert after == before, "the generated index was loaded as a concept"


def test_a_hand_written_index_is_not_overwritten_without_force(bundle):
    (bundle / "index.md").write_text("# My curated index\n", "utf-8")
    with pytest.raises(HandWrittenIndexError, match="not generated by okfquery"):
        write_index(bundle)
    assert (bundle / "index.md").read_text("utf-8") == "# My curated index\n"
    assert write_index(bundle, force=True) is True
    assert (bundle / "index.md").read_text("utf-8").startswith(MARKER)


def test_cli_writes_then_check_passes(bundle, capsys):
    assert main(["index", "--bundle", str(bundle)]) == 0
    assert "wrote" in capsys.readouterr().out
    assert main(["index", "--bundle", str(bundle), "--check"]) == 0


def test_cli_check_fails_when_stale_or_missing(bundle, capsys):
    assert main(["index", "--bundle", str(bundle), "--check"]) == 1
    assert "index.md is missing or stale" in capsys.readouterr().err
    assert not (bundle / "index.md").exists(), "--check must not write"

    assert main(["index", "--bundle", str(bundle)]) == 0
    _concept(bundle, "new", type="runbook", title="New runbook")
    assert main(["index", "--bundle", str(bundle), "--check"]) == 1


def test_cli_refuses_a_hand_written_index(bundle, capsys):
    (bundle / "index.md").write_text("# mine\n", "utf-8")
    assert main(["index", "--bundle", str(bundle)]) == 1
    assert "not generated by okfquery" in capsys.readouterr().err
    assert main(["index", "--bundle", str(bundle), "--force"]) == 0


def test_cli_index_on_a_missing_bundle_exits_2(tmp_path, capsys):
    assert main(["index", "--bundle", str(tmp_path / "nope")]) == 2
    assert "no concepts/ directory" in capsys.readouterr().err


def test_a_multi_line_title_stays_on_one_line(tmp_path):
    _concept(tmp_path, "a", title='"Long\\n  title"')
    text = render_bundle(tmp_path)
    assert "* [Long title](concepts/a/overview.md)" in text, text


def test_a_list_facet_lists_the_concept_under_each_value(tmp_path):
    _concept(tmp_path, "a", title="A", tags="[x, y]")
    _concept(tmp_path, "b", title="B", tags="[y]")
    _concept(tmp_path, "c", title="C", flag="true")
    text = render_bundle(tmp_path, group_by="tags")
    assert "# ['" not in text, text
    x, y = text.split("# y\n")
    assert "(concepts/a/overview.md)" in x and "(concepts/b/overview.md)" not in x
    assert "(concepts/a/overview.md)" in y and "(concepts/b/overview.md)" in y
    assert "# true" in render_bundle(tmp_path, group_by="flag")


def test_a_heading_is_one_line_and_an_empty_value_counts_as_missing(tmp_path):
    _concept(tmp_path, "a", title="A", type='"multi\\nline"')
    _concept(tmp_path, "b", title="B", type='""')
    text = render_bundle(tmp_path)
    assert "# multi line\n" in text, text
    assert "\n# \n" not in text
    assert "# (no type)\n\n* [B](concepts/b/overview.md)" in text, text


def test_grouping_on_a_key_okf_owns_is_rejected(tmp_path, capsys):
    _concept(tmp_path, "a", title="A", type="application")
    with pytest.raises(ValueError, match="'title' is not a facet"):
        render_bundle(tmp_path, group_by="title")
    assert main(["index", "--bundle", str(tmp_path), "--group-by", "type"]) == 2
    assert "'type' is not a facet" in capsys.readouterr().err


def test_backticks_and_angle_brackets_in_a_title_are_escaped(tmp_path):
    _concept(tmp_path, "x", title='"use `foo <b>"', description='"the ` char"')
    assert "* [use \\`foo \\<b>](concepts/x/overview.md) - the ` char" in (
        render_bundle(tmp_path)
    )


def test_an_awkward_path_is_percent_encoded(tmp_path):
    _concept(tmp_path, "a#b c<d>", title="Odd")
    assert "* [Odd](concepts/a%23b%20c%3Cd%3E/overview.md)" in render_bundle(tmp_path)


def test_check_names_a_hand_written_index_instead_of_calling_it_stale(bundle, capsys):
    (bundle / "index.md").write_text("# mine\n", "utf-8")
    assert main(["index", "--bundle", str(bundle), "--check"]) == 1
    err = capsys.readouterr().err
    assert "not generated by okfquery" in err and "--force" in err, err
    assert "missing or stale" not in err


def test_characters_legal_in_a_link_are_left_readable(tmp_path):
    """An agent reads index.md as text and opens the path it sees, so only what
    would break or redirect the link is encoded (found on a web-source bundle,
    whose paths are URL-derived: `@` came out as `%40`)."""
    _concept(tmp_path, "@en.wikipedia.org/wiki/Chargeback", title="Chargeback")
    _concept(tmp_path, "café+menü", title="Menu")
    text = render_bundle(tmp_path)
    assert "(concepts/@en.wikipedia.org/wiki/Chargeback/overview.md)" in text, text
    assert "(concepts/café+menü/overview.md)" in text, text
